export const VIEW_CONTROLLER_TASKS = 'VIEW_CONTROLLER_TASKS'
export const VIEW_CONTROLLER_TASKS_CREATE = 'VIEW_CONTROLLER_TASKS_CREATE'
export const VIEW_CONTROLLER_TASKS_DETAIL = 'VIEW_CONTROLLER_TASKS_DETAIL'
export const VIEW_CONTROLLER_TASKS_CHANGE = 'VIEW_CONTROLLER_TASKS_CHANGE'
